version: 2.0

jobs:
  test_black:
    docker:
      - image: circleci/python:3.6-stretch-node-browsers
    working_directory: ~/dash-sample-apps

    steps:
      - checkout
      - run:
          name: install black
          command: |
            sudo pip install black
      - run:
          name: run black
          command: |
            black . --check
  deploy_to_playground:
    docker:
      - image: circleci/python:3.6-stretch
    working_directory: ~/dash-sample-apps
    steps:
      - checkout
      - run:
          name: Add plotly remote
          command: git remote add playground https://dash-playground.plotly.host/GIT/$CIRCLE_BRANCH
      - run:
          name: Create helper-script
          command: printf '#!/bin/bash\necho username=$PLAYGROUND_DEPLOY_USERNAME\necho password=$PLAYGROUND_DEPLOY_PASSWORD' >> /home/circleci/helper-script.sh
      - run:
          name: Set up git config
          command: git config credential.helper "/bin/bash /home/circleci/helper-script.sh"
      - run:
          name: Deploy
          command: |
            APPS_MODIFIED=$(git diff origin/master origin/$CIRCLE_BRANCH --dirstat=files,1 apps/ | awk '{ split($2,a,"/"); if (length(a[2]) != 0) { print a[2]} } ' | sort -u)
            if [ -z "$APPS_MODIFIED" ]
            then
                  echo "No app change detected. Skipping the deploy.."
                  exit 0
            fi

            git config --global user.email '<>' # Leave email blank
            git config --global user.name "Circle MonoRepo Automatic Deployer"

            for APP in $APPS_MODIFIED
            do
              if [ "$APP" != "$CIRCLE_BRANCH" ]
              then
                echo "appname: $APP is not same as the branchname: $CIRCLE_BRANCH. Not deploying..."
                continue
              fi

              ./deploy "$APP"
              exit 0
            done
            echo "Deploy failed because of a branchname/appname mismatch. Exiting..."
            exit 1
  deploy_to_gallery:
    docker:
      - image: circleci/python:3.6-stretch
    working_directory: ~/dash-sample-apps
    steps:
      - checkout
      - run:
          name: Add plotly remote
          command: git remote add gallery https://dash-playground.plotly.host/GIT/$CIRCLE_BRANCH
      - run:
          name: Create helper-script
          command: printf '#!/bin/bash\necho username=$PLAYGROUND_DEPLOY_USERNAME\necho password=$PLAYGROUND_DEPLOY_PASSWORD' >> /home/circleci/helper-script.sh
      - run:
          name: Set up git config
          command: git config credential.helper "/bin/bash /home/circleci/helper-script.sh"
      - run:
          name: Deploy
          command: |
            APPS_MODIFIED=$(ls apps | grep dash- | sort -u)
            if [ -z "$APPS_MODIFIED" ]
            then
                  echo "No app change detected. Skipping the deploy.."
                  exit 0
            fi

            git config --global user.email '<>' # Leave email blank
            git config --global user.name "Circle MonoRepo Automatic Deployer"

            for APP in $APPS_MODIFIED
            do
              ALLOW_DASHR=false CREATE_APP=false ./deploy "$APP"
            done
      - run:
          name: Push to production
          command: |
              git push --force git@github.com:plotly/dash-sample-apps master:production

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test_black
      - deploy_to_playground:
          requires:
            - test_black
          filters:
            branches:
              ignore:
              - production
              - master
      - deploy_to_gallery:
          requires:
            - test_black
          filters:
            branches:
              only:
              - master
